---

- name: Debian | Ensure dependencies are present
  ansible.builtin.package:
    name: "{{ gift_deps_pkgs | default([]) }}"
    state: present
  register: pkg_result
  until: pkg_result is success

- name: Adding Gift stable repository
  ansible.builtin.apt_repository:
    repo: 'ppa:gift/stable'
    state: present
    codename: "{{ ansible_distribution_release }}"
  notify:
    - Update apt cache
  register: pkg_result
  until: pkg_result is success

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
