---

- name: Debian | Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Ubuntu'
  register: pkg_result
  until: pkg_result is success

- name: Debian | Ensure dependencies are present
  ansible.builtin.package:
    name: "{{ gift_deps_pkgs | default([]) }}"
    state: present
  register: pkg_result
  until: pkg_result is success

- name: Upload gift gpg public key
  ansible.builtin.copy:
    src: 3ed1eaece81894b171d7da5b5e80511b10c598b8.asc
    dest: "/tmp/gift.asc"
    mode: '0644'

- name: Check current gpg keys
  ansible.builtin.command:
    cmd: gpg --list-keys
  changed_when: false
  register: keys

- name: Import local gpg key
  ansible.builtin.command:  # noqa no-changed-when
    cmd: "gpg --import /tmp/gift.asc"
  when:
    - "'3ED1EAECE81894B171D7DA5B5E80511B10C598B8' not in keys.stdout"

- name: Adding Gift stable repository
  ansible.builtin.apt_repository:
    repo: 'ppa:gift/stable'
    state: present
    codename: "{{ ansible_facts['distribution_release'] }}"
  notify:
    - Update apt cache
  register: pkg_result
  until: pkg_result is success

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
