---

- name: adding Gift stable repository
  apt_repository: repo='ppa:gift/stable' state=present
  notify:
    - update apt cache
  register: pkg_result
  until: pkg_result is success

- name: Flush handlers
  meta: flush_handlers
