---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: instance
    image: ${MOLECULE_DISTRO:-ubuntu:18.04}
    # env:
    #   http_proxy: ${http_proxy}
    #   https_proxy: ${https_proxy}
    #   no_proxy: ${no_proxy}
    groups:
      - gift
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: ansible
