---

- name: Verify
  hosts: gift
  tasks:
    - name: Ubuntu
      when: ansible_distribution == 'Ubuntu'
      block:
        - name: List /etc/apt/sources.list.d
          ansible.builtin.command: ls /etc/apt/sources.list.d
          changed_when: false
          register: listd
        - name: List output
          ansible.builtin.debug:
            var: listd

        - name: Fetch content of gift sources.list
          ansible.builtin.slurp:
            src: "/etc/apt/sources.list.d/ppa_gift_stable_{{ ansible_distribution_release }}.list"
          register: sources
        - name: Validate sources
          ansible.builtin.assert:
            that:
              - "'deb http://ppa.launchpad.net/gift' in sources['content'] | b64decode"
    - name: Fedora
      when: ansible_distribution == 'Fedora'
      block:
        - name: Fedora | dnf repolist
          ansible.builtin.command: dnf repolist
          changed_when: false
          failed_when: false
          register: repolist
        - name: Fedora | Validate repolist
          ansible.builtin.assert:
            that:
              - "'group_gift:stable Copr repo for stable owned by @gift' in repolist.stdout"
        - name: List /etc/yum.repos.d/*.repo
          ansible.builtin.command: ls /etc/yum.repos.d/*.repo
          changed_when: false
          failed_when: false
          register: listd
        - name: List output
          ansible.builtin.debug:
            var: listd
